### ISSUE TITLE
AttributeError: `ConfigDict` object has no attribute `weights_dir`

### ISSUE THREAD

**Issue by ccmCCMfk** [Fsoft-AIC/Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds#1]
Thanks for your great work!When I try to run  CUDA_VISIBLE_DEVICES=0 python3 train.py --config ./config/openad_pn2/full_shape_cfg.py --work_dir ./log/openad_pn2/OPENAD_PN2_FULL_SHAPE_Release/ --gpu 0,an error occured,so I replace full_shape_cfg.py with full_shape_open_vocab_cfg.py,it worked,is it OK to do so?

**Comment by ccmCCMfk** [comment]
I noticed that the difference between the two files is about weights_dir.

**Comment by toannguyen1904** [comment]
> Thanks for your great work!When I try to run CUDA_VISIBLE_DEVICES=0 python3 train.py --config ./config/openad_pn2/full_shape_cfg.py --work_dir ./log/openad_pn2/OPENAD_PN2_FULL_SHAPE_Release/ --gpu 0,an error occured,so I replace full_shape_cfg.py with full_shape_open_vocab_cfg.py,it worked,is it OK to do so?

Thank you very much for your interest in our work!
The ```full_shape_open_vocab_cfg.py``` files should be used for zero-shot testing. We forgot to specify the ```weights_dir``` in some configuration files. We have updated them. We hope that the code will run properly now.
