### ISSUE TITLE
Question about the PointTansformer Code

### ISSUE THREAD

**Issue by hschu11** [Fsoft-AIC/Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds#10]
Hi, thanks for your great work. I can not find the code about the PointTransformer Backbone, could you release it for replicate the result.

**Comment by toannguyen1904** [comment]
Hi @hschu11,
We will update the code for Point Transformer as soon as possible. However, you can refer to this [implementation](https://github.com/qq456cvb/Point-Transformers/tree/master/models/Hengshuang) as we adopt it for our work.

Best regards,
Toan.

**Comment by chuhengshuoss** [comment]
Thanks for your reply.
