### ISSUE TITLE
Hi, could u plz give me some ideas on visualize the Point Cloud files with affordance in it, just like the pics in ur article. 

### ISSUE THREAD

**Issue by Tz2H** [Fsoft-AIC/Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds#11]

**Comment by toannguyen1904** [comment]
Hi @Tz2H,
We used [Open3D](https://www.open3d.org/) for our visualization. Our configuration is as follows:
- For material rendering, we use `mat = open3d.visualization.rendering.MaterialRecord()`, with `mat.shader = 'defaultUnlit'` and `mat.point_size = 10.0`
- To construct the point cloud and set its color, we use `open3d.utility.Vector3dVector()`. To visualize cases of multi-affordance detection, you should consider using different colors for different affordance labels.
- For the final visualization, we use `o3d.visualization.draw()`

Best regards,
Toan.
