### ISSUE TITLE
The camera shooting angle and the angle when inputting data into the model are different

### ISSUE THREAD

**Issue by jhcharlotte** [Fsoft-AIC/Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds#3]
Hello, your job is very attractive. I want to apply your work to our work, but I have a question. In your dataset, why do different objects need to be made into a dataset at a fixed angle that is significantly different from the camera shooting angle? This leads to significantly different outputs even when the same object data is input into the model from different angles. Is there any way to solve this problem?

**Comment by toannguyen1904** [comment]
Hi @jhcharlotte. We're pleased to hear that you're interested in our work.

We acknowledge that the point cloud of the object can be captured from different viewpoints. It would be highly beneficial if the model could detect affordances for the object from various angles. Unfortunately, our current work does not account for this feature. However, you can enrich the dataset by randomly rotating the point clouds using different rotation matrices. We believe that training the model on this enriched dataset can help address the task of rotation-invariant affordance detection.

The rotation process can be performed after loading the point cloud, and there's no need to save the new dataset on disk.

We hope this answer addresses your concern.

Best regards,
Toan.

**Comment by mxmdpc** [comment]
Hello, I encountered a problem running the train.py file according to the document. Do you meet the problem of 'dict' object has no attribute 'astype'
