### ISSUE TITLE
'dict' object has no attribute 'astype'

### ISSUE THREAD

**Issue by mxmdpc** [Fsoft-AIC/Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds#4]
Hello, I encountered a problem running the train.py file according to the document. How can I solve it?
![image](https://github.com/Fsoft-AIC/Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds/assets/71645197/11c7fe02-ccdf-4a6f-8813-a8ecb3ed4451)

**Comment by mxmdpc** [comment]
The problem lies in the AffirmanceNet.py line 65: temp = labels.astype(np.float32).reshape(-1, 1)

**Comment by toannguyen1904** [comment]
Hi @mxmdpc, the labels, if loaded properly, should be of type numpy.ndarray. Please carefully double check the data loading process.

Best regards,
Toan.

**Comment by mxmdpc** [comment]
Yes, is numpy.ndarry, but the labels are dict, I donnot know how to change the codes?
![image](https://github.com/Fsoft-AIC/Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds/assets/71645197/23c84539-2fd3-4948-87aa-f91dfbc2da17)
Best regards,
Chen

**Comment by toannguyen1904** [comment]
Did you use our dataset or the 3D AffordanceNet dataset? It seems like you used the latter. Please note that our dataset is different from the 3D AffordanceNet dataset, in which we only keep the argmax for the labels. We provided the Drive link to our dataset in README, please download and use it for this repository.

Best regards,
Toan.

**Comment by mxmdpc** [comment]
I see, thank you very much, I'll try to download and run this program

With respect,
Chen
