### ISSUE TITLE
Question about the data for zero-short.

### ISSUE THREAD

**Issue by hschu11** [Fsoft-AIC/Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds#7]
Hi, thanks for your great work. I can not find the dataset about the Zero-Short OPEN-VOCABULARY DETECTION RESULTS, can you release it for replicate the result.

**Comment by toannguyen1904** [comment]
Hi @hschu11,
Thanks for your interest in our work. We construct the dataset for zero-shot affordance detection based on the provided data in the drive link. Please double-check our source code. To run the zero-shot testing, you just simply need to follow the steps provided in README.

Best regards,
Toan.
