### ISSUE TITLE
Checkpoint to the model trained by you for the paper

### ISSUE THREAD

**Issue by advilema** [Fsoft-AIC/Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds#9]
Hi! Thanks a lot for sharing this code :)
Can you please provide the weights of the model that you trained for the paper submission in order to test it? I couldn't find them anywhere.
Thanks a lot in advance!

**Comment by toannguyen1904** [comment]
Hi @advilema ,
The trained weights were unluckily unintentionally discarded. However, you can follow our training steps to reproduce the results.

Best regards,
Toan.

**Comment by toannguyen1904** [comment]
Hi,
Sorry for the late response.
We have currently retrieved the trained weights and will update them soon. There are some restriction made by our department which may cause the update delayed. Please stay tuned or you can follow our training steps for your experiments; it will not take long.

Best regards,
Toan.

**Comment by toannguyen1904** [comment]
Hi @advilema, the checkpoints of our best models for full-shape and partial-view tasks can be downloaded at this [drive](https://drive.google.com/drive/folders/17895vwgGHfIlDj3q0a7BOg6cotH5RTjm?usp=sharing).

Thanks for your patience.
Toan.
